### ISSUE TITLE
hello.o: error adding symbols: File in wrong format

### ISSUE THREAD

**Issue by TATAyu0413** [Lichtso/riscv-llvm-templates#1]
yu@yu:~/Desktop$ /home/yu/toolchain/bin/riscv64-unknown-elf-gcc hello.o -o hello -march=rv64imac -mabi=lp64
/home/yu/toolchain/lib/gcc/riscv64-unknown-elf/7.1.0/../../../../riscv64-unknown-elf/bin/ld: hello.o: Relocations in generic ELF (EM: 62)
/home/yu/toolchain/lib/gcc/riscv64-unknown-elf/7.1.0/../../../../riscv64-unknown-elf/bin/ld: hello.o: Relocations in generic ELF (EM: 62)
hello.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
How can I resolve it? Thank you so much!

**Comment by Lichtso** [comment]
This repository is about the use of the LLVM toolchain so the question might be better asked in https://github.com/riscv/riscv-gnu-toolchain directly.

As for your specific error: I suspect you forgot to set some flags like '-nostdlib' to prevent the linker form trying to link your installed standard library (e.g. X86 or AMD64) against the RISC-V object file which won't work. Take a look over at the CFLAGS and LDFLAGS in the Makefile of this repo: https://github.com/michaeljclark/riscv-probe/blob/master/Makefile
